server:
  port: 6001

spring:
  application:
    name: cloud-zuul-server

eureka:
  client:
    service-url:
      #表示是否将自己注册为EurekaService,默认为true
      register-with-eureka: true
      #是否从EurekaService住抓取已有的注册信息，默认为true。集群必须设置为true
      fetch-registry: true
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: cloud-zuul
    prefer-ip-address: true
zuul:
  ignored-services: "*"
  routes:
    payment:
      serviceId: cloud-payment-service
      path: /payment/**
    order:
      serviceId: cloud-order-service
      path: /order/**

info:
    app.name: cloud-zuul-server
    company.name: www.wongchan.com
    build.artifactId: $project.artifactId$
    build.version: $project.version$

logging:
  config: